experimentName: gnn_nni
trialConcurrency: 4  # 根据您的GPU数量设置
maxExperimentDuration: 24h
maxTrialNumber: 200
# maxTrialNumPerGpu: 1
searchSpaceFile: gnn_search_space.json
trialCommand: python main.py --config config/gnn.yaml
trialCodeDirectory: .
trialGpuNumber: 1  # 每个试验只使用1张GPU
tuner:
  name: Random
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
  useActiveGpu: true
