experimentName: unigopooling_nni
trialConcurrency: 4  # 根据您的GPU数量设置
maxExperimentDuration: 96h
maxTrialNumber: 200
# maxTrialNumPerGpu: 1
searchSpaceFile: unigopoolingv2_search_space.json
trialCommand: python main.py --config config/unigo_pooling_v2.yaml
trialCodeDirectory: .
trialGpuNumber: 1  # 每个试验只使用1张GPU
tuner:
  name: Random
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
  useActiveGpu: true