experimentName: unigosage_nni
trialConcurrency: 4  
maxExperimentDuration: 96h
maxTrialNumber: 200
searchSpaceFile: unigo_search_space.json
trialCommand: python main.py --config config/unigo_sage.yaml
trialCodeDirectory: .
trialGpuNumber: 1  
tuner:
  name: Random
  classArgs:
    optimize_mode: minimize
trainingService:
  platform: local
  useActiveGpu: true